-- 代码生成模块多类型支持 - 数据库变更脚本
-- 日期：2026-04-08

-- GEN_BASIC 表新增字段（放在 AUTHOR_NAME 后面，依次排列）
ALTER TABLE GEN_BASIC ADD COLUMN GEN_TYPE VARCHAR(50) DEFAULT 'TABLE' COMMENT '生成类型：TABLE单表格/TREE单树表/LEFT_TREE_TABLE左树右表/MASTER_DETAIL主子表' AFTER AUTHOR_NAME;
ALTER TABLE GEN_BASIC ADD COLUMN TREE_PARENT_FIELD VARCHAR(200) COMMENT '树父级字段名（单树表专用，如PARENT_ID）' AFTER GEN_TYPE;
ALTER TABLE GEN_BASIC ADD COLUMN TREE_NAME_FIELD VARCHAR(200) COMMENT '树显示名称字段名（单树表专用，如NAME）' AFTER TREE_PARENT_FIELD;
ALTER TABLE GEN_BASIC ADD COLUMN SUB_DB_TABLE VARCHAR(200) COMMENT '子表表名（双表专用）' AFTER TREE_NAME_FIELD;
ALTER TABLE GEN_BASIC ADD COLUMN SUB_DB_TABLE_KEY VARCHAR(200) COMMENT '子表主键（双表专用）' AFTER SUB_DB_TABLE;
ALTER TABLE GEN_BASIC ADD COLUMN SUB_FOREIGN_KEY VARCHAR(200) COMMENT '子表关联主表的外键字段名（双表专用）' AFTER SUB_DB_TABLE_KEY;
ALTER TABLE GEN_BASIC ADD COLUMN SUB_CLASS_NAME VARCHAR(200) COMMENT '子表类名（双表专用）' AFTER SUB_FOREIGN_KEY;
ALTER TABLE GEN_BASIC ADD COLUMN SUB_FUNCTION_NAME VARCHAR(200) COMMENT '子表功能名（双表专用）' AFTER SUB_CLASS_NAME;
ALTER TABLE GEN_BASIC ADD COLUMN SUB_BUS_NAME VARCHAR(200) COMMENT '子表业务名（双表专用）' AFTER SUB_FUNCTION_NAME;

-- GEN_CONFIG 表新增字段
ALTER TABLE GEN_CONFIG ADD COLUMN TABLE_TYPE VARCHAR(20) DEFAULT 'MAIN' COMMENT '所属表类型：MAIN主表/SUB子表' AFTER SORT_CODE;

-- 为已有数据设置默认值
UPDATE GEN_BASIC SET GEN_TYPE = 'TABLE' WHERE GEN_TYPE IS NULL;
UPDATE GEN_CONFIG SET TABLE_TYPE = 'MAIN' WHERE TABLE_TYPE IS NULL;
