#指定Java的版本
-target 17
#proguard会对代码进行优化压缩，他会删除从未使用的类或者类成员变量等
-dontshrink
#是否关闭字节码级别的优化，如果不开启则设置如下配置
-dontoptimize
#保持目录结构，否则spring的自动注入无法使用
-keepdirectories
# 对于类成员的命名的混淆采取唯一策略
#-useuniqueclassmembernames
#混淆类名之后，对使用Class.forName('className')之类的地方进行相应替代
-adaptclassstrings
#混淆时不生成大小写混合的类名，默认是可以大小写混合
#-dontusemixedcaseclassnames
#对异常、注解信息予以保留
-keepattributes  Exceptions,InnerClasses,Signature,Deprecated,SourceFile,LineNumberTable,*Annotation*,EnclosingMethod
# 此选项将保存接口中的所有原始名称（不混淆）-->
-keepnames interface ** { *; }
#保留参数名，因为控制器，或者Mybatis等接口的参数如果混淆会导致无法接受参数，xml文件找不到参数
-keepparameternames
# 保留枚举成员及方法
#-keepclassmembers enum * { *; }
# 不混淆所有的set/get方法，毕竟项目中使用的部分第三方框架（例如Shiro）会用到大量的set/get映射
#-keepclassmembers public class * {void set*(***);*** get*();}
# 不混淆所有类,保存原始定义的注释-
-keepclassmembers class * {
@org.springframework.context.annotation.Bean *;
@org.springframework.beans.factory.annotation.Autowired *;
@org.springframework.beans.factory.annotation.Value *;
@org.springframework.web.socket.config.annotation.EnableWebSocket *;
@org.springframework.web.socket.config.annotation.WebSocketConfigurer *;
@org.springframework.web.socket.config.annotation.WebSocketHandlerRegistry *;
@org.springframework.stereotype.Component *;
@org.springframework.context.annotation.Configuration *;
@org.springframework.boot.context.properties.ConfigurationProperties *;
@org.springframework.stereotype.Service *;
@org.springframework.stereotype.Component *;
@org.springframework.scheduling.annotation.Scheduled *;
@lombok.RequiredArgsConstructor *;
@org.springframework.validation.annotation.Validated *;
@org.springframework.web.bind.annotation.GetMapping *;
@org.springframework.web.bind.annotation.PostMapping *;
@org.springframework.web.bind.annotation.RequestBody *;
@org.springframework.web.bind.annotation.RestController *;
@vip.xiaonuo.common.annotation.CommonLog *;
@cn.dev33.satoken.annotation.SaCheckPermission *;
@io.swagger.v3.oas.annotations.Operation *;
@io.swagger.v3.oas.annotations.tags.Tag *;
@jakarta.annotation.Resource *;
@jakarta.validation.Valid *;
@jakarta.validation.constraints.NotEmpty *;
@lombok.extern.slf4j.Slf4j *;
}
#保留Serializable序列化的类不被混淆
-keepclassmembers class * implements java.io.Serializable {*;}

#忽略warn消息
-ignorewarnings
#忽略note消息
-dontnote
#打印配置信息
-printconfiguration
#需要保留的文件
-keep class vip.xiaonuo.im.core.config.* {*;}
-keep class vip.xiaonuo.im.modular.**.service.impl.* {*;}
-keep class vip.xiaonuo.im.modular.**.controller.* {*;}
-keep class vip.xiaonuo.im.modular.**.mapper.* {*;}
-keep class vip.xiaonuo.im.modular.**.entity.* {*;}
-keep class vip.xiaonuo.im.modular.**.param.* {*;}
-keep class vip.xiaonuo.im.core.handler.* {*;}
#所有集成BaseService的类保留名称
-keepnames class * extends com.zxy.mom.sdk.common.service.
#保留启动类
-keep public class vip.xiaonuo.im.core.config.WebSocketConfiguration  {*;}
